import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Layout
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.register': 'Register Device',
    'system.title': 'IT System',
    'system.subtitle': 'Device Management',
    'system.version': 'Version 1.0.0',
    
    // Dashboard
    'dashboard.title': 'Monitoring Dashboard',
    'dashboard.subtitle': 'Real-time device status overview',
    'dashboard.totalDevices': 'Total Devices',
    'dashboard.devicesMonitored': 'Devices monitored',
    'dashboard.onlineDevices': 'Online Devices',
    'dashboard.availability': 'availability',
    'dashboard.offlineDevices': 'Offline Devices',
    'dashboard.requireAttention': 'Require attention',
    'dashboard.criticalDisks': 'Critical Disks',
    'dashboard.diskUsage': 'Disk usage > 85%',
    'dashboard.search': 'Search by hostname, user or IP...',
    'dashboard.monitoredDevices': 'Monitored Devices',
    'dashboard.status': 'Status',
    'dashboard.hostname': 'Hostname',
    'dashboard.user': 'User',
    'dashboard.employee': 'Employee',
    'dashboard.ip': 'IP',
    'dashboard.location': 'Location',
    'dashboard.cpu': 'CPU',
    'dashboard.ram': 'RAM',
    'dashboard.disk': 'Disk',
    'dashboard.actions': 'Actions',
    'dashboard.viewDetails': 'View Details',
    'dashboard.noResults': 'No devices found matching the search',
    'dashboard.cores': 'cores',
    
    // Monitoring Details Modal
    'modal.general': 'General',
    'modal.hardware': 'Hardware',
    'modal.disks': 'Disks',
    'modal.system': 'System',
    'modal.status': 'Status',
    'modal.user': 'User',
    'modal.ip': 'IP Address',
    'modal.mac': 'MAC Address',
    'modal.platform': 'Platform',
    'modal.uptime': 'Uptime',
    'modal.location': 'Location',
    'modal.notSpecified': 'Not specified',
    'modal.lastConnection': 'Last Connection',
    'modal.registrationDate': 'Registration Date',
    'modal.cpu': 'Processor (CPU)',
    'modal.model': 'Model',
    'modal.cores': 'Cores',
    'modal.speed': 'Speed',
    'modal.temperature': 'Temperature',
    'modal.notAvailable': 'Not available',
    'modal.ram': 'Memory RAM',
    'modal.memoryUsage': 'Memory usage',
    'modal.free': 'Free',
    'modal.inUse': 'In use',
    'modal.disk': 'Disk',
    'modal.diskUsage': 'Disk usage',
    'modal.used': 'Used',
    'modal.total': 'Total',
    'modal.edition': 'Edition',
    'modal.version': 'Version',
    'modal.buildInstalled': 'Build Installed',
    'modal.specification': 'Specification',
    'modal.deviceId': 'Device ID',
    'modal.productId': 'Product ID',
    
    // Inventory
    'inventory.title': 'Device Inventory',
    'inventory.subtitle': 'Assigned PC management and documentation',
    'inventory.totalDevices': 'Total Devices',
    'inventory.active': 'Active',
    'inventory.signed': 'Signed',
    'inventory.warrantyExpiring': 'Warranty Expiring',
    'inventory.expiringSoon': 'Expiring soon',
    'inventory.search': 'Search by ID, employee, department or service tag...',
    'inventory.status': 'Status',
    'inventory.allStatus': 'All',
    'inventory.activeStatus': 'Active',
    'inventory.maintenanceStatus': 'Maintenance',
    'inventory.inactiveStatus': 'Inactive',
    'inventory.assignedPCs': 'Assigned PCs',
    'inventory.id': 'ID',
    'inventory.employee': 'Employee',
    'inventory.department': 'Department',
    'inventory.plant': 'Plant',
    'inventory.type': 'Type',
    'inventory.brand': 'Brand',
    'inventory.model': 'Model',
    'inventory.letter': 'Letter',
    'inventory.actions': 'Actions',
    'inventory.details': 'Details',
    'inventory.noResults': 'No devices found matching the filters',
    'inventory.yes': 'Yes',
    'inventory.sign': 'Sign',
    
    // Device Details Modal
    'deviceModal.title': 'Device Details',
    'deviceModal.showPasswords': 'Show Passwords',
    'deviceModal.hidePasswords': 'Hide Passwords',
    'deviceModal.info': 'Information',
    'deviceModal.warranty': 'Warranty',
    'deviceModal.windows': 'Windows',
    'deviceModal.access': 'Access',
    'deviceModal.documents': 'Documents',
    'deviceModal.status': 'Status',
    'deviceModal.employee': 'Employee',
    'deviceModal.department': 'Department',
    'deviceModal.plant': 'Plant',
    'deviceModal.type': 'Type',
    'deviceModal.brand': 'Brand',
    'deviceModal.model': 'Model',
    'deviceModal.serviceTag': 'Service Tag',
    'deviceModal.deviceName': 'Device Name',
    'deviceModal.specifications': 'Specifications',
    'deviceModal.purchaseDate': 'Purchase Date',
    'deviceModal.assignmentDate': 'Assignment Date',
    'deviceModal.warrantyStart': 'Warranty Start',
    'deviceModal.warrantyEnd': 'Warranty End',
    'deviceModal.renewalStatus': 'Renewal Status',
    'deviceModal.biosPassword': 'BIOS Password',
    'deviceModal.officeLicense': 'Office License',
    'deviceModal.windowsUser': 'Windows User',
    'deviceModal.windowsPassword': 'Windows Password',
    'deviceModal.adminUser': 'Admin User',
    'deviceModal.adminPassword': 'Admin Password',
    'deviceModal.enrolledEmail': 'Enrolled Email',
    'deviceModal.enrolledPassword': 'Enrolled Password',
    'deviceModal.exmailEmail': 'Exmail Email',
    'deviceModal.exmailPassword': 'Exmail Password',
    'deviceModal.nasUser': 'NAS User',
    'deviceModal.nasPassword': 'NAS Password',
    'deviceModal.vpnUser': 'VPN User',
    'deviceModal.vpnPassword': 'VPN Password',
    'deviceModal.osticketUser': 'OSTicket User',
    'deviceModal.osticketPassword': 'OSTicket Password',
    'deviceModal.responsibilityLetter': 'Responsibility Letter',
    'deviceModal.download': 'Download',
    'deviceModal.upload': 'Upload',
    'deviceModal.notAvailable': 'Not available',
    'deviceModal.file': 'File',
    'deviceModal.bitlockerKey': 'BitLocker Key',
    'deviceModal.signatureStatus': 'Signature Status',
    'deviceModal.documentSigned': 'Document signed',
    'deviceModal.pendingSignature': 'Pending signature',
    'deviceModal.signed': 'Signed',
    'deviceModal.sign': 'Sign',
    'deviceModal.exitPermit': 'Plant Exit Permit',
    'deviceModal.exitPermitGranted': 'Device is authorized to leave the facilities',
    'deviceModal.exitPermitDenied': 'Device CANNOT leave the facilities',
    'deviceModal.authorized': 'Authorized',
    'deviceModal.notAuthorized': 'Not Authorized',
    
    // QR Modal
    'qrModal.title': 'QR Code',
    'qrModal.employee': 'Employee',
    'qrModal.device': 'Device',
    'qrModal.serviceTag': 'Service Tag',
    'qrModal.exitPermit': 'Exit Permit',
    'qrModal.authorizedExit': '✓ Authorized to leave',
    'qrModal.notAuthorizedExit': '✗ Not authorized to leave',
    'qrModal.download': 'Download QR Code',
    
    // Register
    'register.title': 'Register Computer Equipment',
    'register.subtitle': 'Complete the information to register a new device',
    'register.deviceInfo': 'Device Information',
    'register.employee': 'Employee',
    'register.device': 'Device',
    'register.warranty': 'Warranty',
    'register.windows': 'Windows',
    'register.access': 'Access',
    'register.employeeName': 'Employee Name',
    'register.employeeNamePlaceholder': 'e.g: John Doe',
    'register.department': 'Department',
    'register.selectDepartment': 'Select department',
    'register.plant': 'Plant',
    'register.selectPlant': 'Select plant',
    'register.deviceType': 'Device Type',
    'register.selectType': 'Select type',
    'register.brand': 'Brand',
    'register.selectBrand': 'Select brand',
    'register.model': 'Model',
    'register.modelPlaceholder': 'e.g: Latitude 5430',
    'register.serviceTag': 'Service Tag',
    'register.serviceTagPlaceholder': 'e.g: HVRF924',
    'register.deviceName': 'Device Name',
    'register.deviceNamePlaceholder': 'e.g: FSMXADMIN',
    'register.purchaseDate': 'Purchase Date',
    'register.assignmentDate': 'Assignment Date',
    'register.basicSpecs': 'Basic Specifications',
    'register.specsPlaceholder': 'e.g: Intel i5-1235U, 16GB RAM, 256GB SSD',
    'register.warrantyStart': 'Warranty Start',
    'register.warrantyEnd': 'Warranty End',
    'register.renewalStatus': 'Renewal Status',
    'register.selectStatus': 'Select status',
    'register.biosPassword': 'BIOS Password',
    'register.officeLicense': 'Office License',
    'register.officeLicensePlaceholder': 'XXXXX-XXXXX-XXXXX-XXXXX-XXXXX',
    'register.windowsUser': 'Windows User',
    'register.windowsUserPlaceholder': 'user.windows',
    'register.windowsPassword': 'Windows Password',
    'register.adminUser': 'Admin User',
    'register.adminUserPlaceholder': 'admin.local',
    'register.adminPassword': 'Admin Password',
    'register.enrolledEmail': 'Enrolled Email',
    'register.enrolledEmailPlaceholder': 'user@company.com',
    'register.enrolledPassword': 'Enrolled Password',
    'register.exmailEmail': 'Exmail Email',
    'register.exmailEmailPlaceholder': 'user@exmail.company.com',
    'register.exmailPassword': 'Exmail Password',
    'register.nasUser': 'NAS User',
    'register.nasUserPlaceholder': 'user.nas',
    'register.nasPassword': 'NAS Password',
    'register.vpnUser': 'VPN User',
    'register.vpnUserPlaceholder': 'user.vpn',
    'register.vpnPassword': 'VPN Password',
    'register.osticketUser': 'OSTicket User',
    'register.osticketUserPlaceholder': 'user.osticket',
    'register.osticketPassword': 'OSTicket Password',
    'register.saveDevice': 'Save Device',
    'register.clearForm': 'Clear Form',
    'register.errorEmployee': 'Please complete the employee information',
    'register.errorDevice': 'Please complete the device information',
    'register.successTitle': 'Device registered successfully',
    'register.successDescription': 'assigned to',
    
    // Common
    'common.online': '🟢 Online',
    'common.offline': '🔴 Offline',
    'common.active': 'Active',
    'common.maintenance': 'Maintenance',
    'common.inactive': 'Inactive',
    'common.valid': 'Valid',
    'common.expiring': 'Expiring',
    'common.expired': 'Expired',
    'common.renewed': 'Renewed',
  },
  es: {
    // Layout
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventario',
    'nav.register': 'Registrar Equipo',
    'system.title': 'Sistema IT',
    'system.subtitle': 'Gestión de Equipos',
    'system.version': 'Versión 1.0.0',
    
    // Dashboard
    'dashboard.title': 'Dashboard de Monitoreo',
    'dashboard.subtitle': 'Vista en tiempo real del estado de los equipos',
    'dashboard.totalDevices': 'Total de Equipos',
    'dashboard.devicesMonitored': 'Equipos monitoreados',
    'dashboard.onlineDevices': 'Equipos Online',
    'dashboard.availability': 'disponibilidad',
    'dashboard.offlineDevices': 'Equipos Offline',
    'dashboard.requireAttention': 'Requieren atención',
    'dashboard.criticalDisks': 'Discos Críticos',
    'dashboard.diskUsage': 'Uso de disco > 85%',
    'dashboard.search': 'Buscar por hostname, usuario o IP...',
    'dashboard.monitoredDevices': 'Equipos Monitoreados',
    'dashboard.status': 'Estado',
    'dashboard.hostname': 'Hostname',
    'dashboard.user': 'Usuario',
    'dashboard.employee': 'Empleado',
    'dashboard.ip': 'IP',
    'dashboard.location': 'Ubicación',
    'dashboard.cpu': 'CPU',
    'dashboard.ram': 'RAM',
    'dashboard.disk': 'Disco',
    'dashboard.actions': 'Acciones',
    'dashboard.viewDetails': 'Ver Detalles',
    'dashboard.noResults': 'No se encontraron equipos que coincidan con la búsqueda',
    'dashboard.cores': 'núcleos',
    
    // Monitoring Details Modal
    'modal.general': 'General',
    'modal.hardware': 'Hardware',
    'modal.disks': 'Discos',
    'modal.system': 'Sistema',
    'modal.status': 'Estado',
    'modal.user': 'Usuario',
    'modal.ip': 'Dirección IP',
    'modal.mac': 'Dirección MAC',
    'modal.platform': 'Plataforma',
    'modal.uptime': 'Tiempo Encendido',
    'modal.location': 'Ubicación',
    'modal.notSpecified': 'No especificada',
    'modal.lastConnection': 'Última Conexión',
    'modal.registrationDate': 'Fecha de Registro',
    'modal.cpu': 'Procesador (CPU)',
    'modal.model': 'Modelo',
    'modal.cores': 'Núcleos',
    'modal.speed': 'Velocidad',
    'modal.temperature': 'Temperatura',
    'modal.notAvailable': 'No disponible',
    'modal.ram': 'Memoria RAM',
    'modal.memoryUsage': 'Uso de memoria',
    'modal.free': 'Libre',
    'modal.inUse': 'En uso',
    'modal.disk': 'Disco',
    'modal.diskUsage': 'Uso del disco',
    'modal.used': 'Usado',
    'modal.total': 'Total',
    'modal.edition': 'Edición',
    'modal.version': 'Versión',
    'modal.buildInstalled': 'Build Instalado',
    'modal.specification': 'Especificación',
    'modal.deviceId': 'ID de Dispositivo',
    'modal.productId': 'ID de Producto',
    
    // Inventory
    'inventory.title': 'Inventario de Equipos',
    'inventory.subtitle': 'Gestión de PCs asignadas y documentación',
    'inventory.totalDevices': 'Total Equipos',
    'inventory.active': 'Activos',
    'inventory.signed': 'Firmados',
    'inventory.warrantyExpiring': 'Garantías por Vencer',
    'inventory.expiringSoon': 'Por vencer pronto',
    'inventory.search': 'Buscar por ID, empleado, departamento o service tag...',
    'inventory.status': 'Estado',
    'inventory.allStatus': 'Todos',
    'inventory.activeStatus': 'Activo',
    'inventory.maintenanceStatus': 'Mantenimiento',
    'inventory.inactiveStatus': 'Inactivo',
    'inventory.assignedPCs': 'PCs Asignadas',
    'inventory.id': 'ID',
    'inventory.employee': 'Empleado',
    'inventory.department': 'Departamento',
    'inventory.plant': 'Planta',
    'inventory.type': 'Tipo',
    'inventory.brand': 'Marca',
    'inventory.model': 'Modelo',
    'inventory.letter': 'Carta',
    'inventory.actions': 'Acciones',
    'inventory.details': 'Detalles',
    'inventory.noResults': 'No se encontraron equipos que coincidan con los filtros',
    'inventory.yes': 'Sí',
    'inventory.sign': 'Firmar',
    
    // Device Details Modal
    'deviceModal.title': 'Detalles del Equipo',
    'deviceModal.showPasswords': 'Mostrar Contraseñas',
    'deviceModal.hidePasswords': 'Ocultar Contraseñas',
    'deviceModal.info': 'Información',
    'deviceModal.warranty': 'Garantía',
    'deviceModal.windows': 'Windows',
    'deviceModal.access': 'Accesos',
    'deviceModal.documents': 'Documentos',
    'deviceModal.status': 'Estado',
    'deviceModal.employee': 'Empleado',
    'deviceModal.department': 'Departamento',
    'deviceModal.plant': 'Planta',
    'deviceModal.type': 'Tipo',
    'deviceModal.brand': 'Marca',
    'deviceModal.model': 'Modelo',
    'deviceModal.serviceTag': 'Service Tag',
    'deviceModal.deviceName': 'Nombre del Equipo',
    'deviceModal.specifications': 'Especificaciones',
    'deviceModal.purchaseDate': 'Fecha de Compra',
    'deviceModal.assignmentDate': 'Fecha de Asignación',
    'deviceModal.warrantyStart': 'Inicio de Garantía',
    'deviceModal.warrantyEnd': 'Fin de Garantía',
    'deviceModal.renewalStatus': 'Estado de Renovación',
    'deviceModal.biosPassword': 'BIOS Password',
    'deviceModal.officeLicense': 'Licencia Office',
    'deviceModal.windowsUser': 'Usuario Windows',
    'deviceModal.windowsPassword': 'Contraseña Windows',
    'deviceModal.adminUser': 'Usuario Admin',
    'deviceModal.adminPassword': 'Contraseña Admin',
    'deviceModal.enrolledEmail': 'Correo Enrollado',
    'deviceModal.enrolledPassword': 'Contraseña Enrollado',
    'deviceModal.exmailEmail': 'Correo Exmail',
    'deviceModal.exmailPassword': 'Contraseña Exmail',
    'deviceModal.nasUser': 'Usuario NAS',
    'deviceModal.nasPassword': 'Contraseña NAS',
    'deviceModal.vpnUser': 'Usuario VPN',
    'deviceModal.vpnPassword': 'Contraseña VPN',
    'deviceModal.osticketUser': 'Usuario OSTicket',
    'deviceModal.osticketPassword': 'Contraseña OSTicket',
    'deviceModal.responsibilityLetter': 'Carta Responsiva',
    'deviceModal.download': 'Descargar',
    'deviceModal.upload': 'Subir',
    'deviceModal.notAvailable': 'No disponible',
    'deviceModal.file': 'Archivo',
    'deviceModal.bitlockerKey': 'Clave BitLocker',
    'deviceModal.signatureStatus': 'Estado de Firma',
    'deviceModal.documentSigned': 'Documento firmado',
    'deviceModal.pendingSignature': 'Pendiente de firma',
    'deviceModal.signed': 'Firmado',
    'deviceModal.sign': 'Firmar',
    'deviceModal.exitPermit': 'Permiso de Salida de Planta',
    'deviceModal.exitPermitGranted': 'El equipo cuenta con permiso para salir de las instalaciones',
    'deviceModal.exitPermitDenied': 'El equipo NO puede salir de las instalaciones',
    'deviceModal.authorized': 'Autorizado',
    'deviceModal.notAuthorized': 'No Autorizado',
    
    // QR Modal
    'qrModal.title': 'Código QR',
    'qrModal.employee': 'Empleado',
    'qrModal.device': 'Equipo',
    'qrModal.serviceTag': 'Service Tag',
    'qrModal.exitPermit': 'Permiso de Salida',
    'qrModal.authorizedExit': '✓ Autorizado para salir',
    'qrModal.notAuthorizedExit': '✗ No autorizado para salir',
    'qrModal.download': 'Descargar Código QR',
    
    // Register
    'register.title': 'Registrar Equipo de Cómputo',
    'register.subtitle': 'Completa la información para registrar un nuevo equipo',
    'register.deviceInfo': 'Información del Equipo',
    'register.employee': 'Empleado',
    'register.device': 'Equipo',
    'register.warranty': 'Garantía',
    'register.windows': 'Windows',
    'register.access': 'Accesos',
    'register.employeeName': 'Nombre del Empleado',
    'register.employeeNamePlaceholder': 'Ej: Juan Pérez García',
    'register.department': 'Departamento',
    'register.selectDepartment': 'Seleccionar departamento',
    'register.plant': 'Planta',
    'register.selectPlant': 'Seleccionar planta',
    'register.deviceType': 'Tipo de Equipo',
    'register.selectType': 'Seleccionar tipo',
    'register.brand': 'Marca',
    'register.selectBrand': 'Seleccionar marca',
    'register.model': 'Modelo',
    'register.modelPlaceholder': 'Ej: Latitude 5430',
    'register.serviceTag': 'Service Tag',
    'register.serviceTagPlaceholder': 'Ej: HVRF924',
    'register.deviceName': 'Nombre del Equipo',
    'register.deviceNamePlaceholder': 'Ej: FSMXADMIN',
    'register.purchaseDate': 'Fecha de Compra',
    'register.assignmentDate': 'Fecha de Asignación',
    'register.basicSpecs': 'Especificaciones Básicas',
    'register.specsPlaceholder': 'Ej: Intel i5-1235U, 16GB RAM, 256GB SSD',
    'register.warrantyStart': 'Inicio de Garantía',
    'register.warrantyEnd': 'Fin de Garantía',
    'register.renewalStatus': 'Estado de Renovación',
    'register.selectStatus': 'Seleccionar estado',
    'register.biosPassword': 'BIOS Password',
    'register.officeLicense': 'Licencia Office',
    'register.officeLicensePlaceholder': 'XXXXX-XXXXX-XXXXX-XXXXX-XXXXX',
    'register.windowsUser': 'Usuario Windows',
    'register.windowsUserPlaceholder': 'usuario.windows',
    'register.windowsPassword': 'Contraseña Windows',
    'register.adminUser': 'Usuario Admin',
    'register.adminUserPlaceholder': 'admin.local',
    'register.adminPassword': 'Contraseña Admin',
    'register.enrolledEmail': 'Correo Enrollado',
    'register.enrolledEmailPlaceholder': 'usuario@empresa.com',
    'register.enrolledPassword': 'Contraseña Enrollado',
    'register.exmailEmail': 'Correo Exmail',
    'register.exmailEmailPlaceholder': 'usuario@exmail.empresa.com',
    'register.exmailPassword': 'Contraseña Exmail',
    'register.nasUser': 'Usuario NAS',
    'register.nasUserPlaceholder': 'usuario.nas',
    'register.nasPassword': 'Contraseña NAS',
    'register.vpnUser': 'Usuario VPN',
    'register.vpnUserPlaceholder': 'usuario.vpn',
    'register.vpnPassword': 'Contraseña VPN',
    'register.osticketUser': 'Usuario OSTicket',
    'register.osticketUserPlaceholder': 'usuario.osticket',
    'register.osticketPassword': 'Contraseña OSTicket',
    'register.saveDevice': 'Guardar Equipo',
    'register.clearForm': 'Limpiar Formulario',
    'register.errorEmployee': 'Por favor, completa la información del empleado',
    'register.errorDevice': 'Por favor, completa la información del equipo',
    'register.successTitle': 'Equipo registrado exitosamente',
    'register.successDescription': 'asignado a',
    
    // Common
    'common.online': '🟢 Online',
    'common.offline': '🔴 Offline',
    'common.active': 'Activo',
    'common.maintenance': 'Mantenimiento',
    'common.inactive': 'Inactivo',
    'common.valid': 'Vigente',
    'common.expiring': 'Por Vencer',
    'common.expired': 'Vencida',
    'common.renewed': 'Renovada',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es'); // Cambiado a español por defecto

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}